# v1_deployment.yml
---

- create:
    name: frontend
    namespace: myproject
    pod_metadata_labels:
      name: frontend
    pod_containers:
    - name: helloworld
      image: openshift/origin-ruby-sample
      ports:
      - container_port: 8080
        protocol: TCP
    replicas: 5
    selector:
      name: frontend
    triggers:
    - type: ConfigChange
    - type: ImageChange
      image_change_params:
        automatic: true
        container_names:
        - helloworld
        _from:
          kind: ImageStreamTag
          name: origin-ruby-sample:latest
    deployment_strategy_type: Rolling
  name: Create deployment config

- patch:
    name: frontend
    namespace: myproject
    pod_metadata_labels:
      name: frontend
    pod_containers:
    - name: helloworld
      image: "openshift/origin-ruby-sample:v1.0"
      ports:
      - container_port: 8080
        protocol: TCP
      - container_port: 9000
        protocol: UDP
    replicas: 3
  name: Create deployment config
